### ISSUE TITLE
events : order by start time in home, agenda; hide finished events in a dropdown

### ISSUE THREAD

**Issue by agilare** [agilare/ladecadanse#21]
From the beginning of La décadanse events are ordered by date of addition in homepage and agenda. It's natural and proven for users looking for fresh events day to day, but it has some defects.

Some organizers add their events twice : one first time 1-2 weeks before the event and then 1-2 days before, in order to be well positioned, visible. Someones don't remove the first instance of the event.
When users look for event, particularly in the evening, a lot of events are already finished, then not very useful.

Changing this order by date of event would stay natural and allow some improvements. Looking a the list of event by date of addition would remain possible.

# Specifications

Layout in home : 

> # Aujourd'hui
> 
> ## Déjà passés (8) v
> ## À venir (17)
> event1
> event2
> ...

- passed events are hidden and can be viewed by clicking on the dropdown ("Déjà passés")
- number after "Déjà passés" is the nb of events passed
- events are considered as passed, according their end time, if event is without end time, show it normally
- order events by start time, if event is without start time show it in the end of the list
- passed events : one dropdown per category (Fêtes, Ciné...) or one only for all ?
-  when adding a new event make end time mandatory if start time is filled ?

# Tasks
- [ ] add a tab menu or a `<select>`of order of events : Début | Date d'ajout
- [ ] dropdown of passed events
- [ ] mark passed events (gray ?)
- [ ] update query
- [ ] mark current events (yellow ?)
- [ ] add : "Tout" showing all events in region menu

**Comment by agilare** [comment]
Qu'en dites-vous ? @Angelinsky7 @VonUniGE

**Comment by Angelinsky7** [comment]
Je mettrais les "déjà passés" à la fin plutot que au début... (même si ils sont cachés)....
Et une fois de plus j'aurais plutôt tendance à afficher les événements de manière aléatoire afin d'éviter les comportements actuels (comme créer les évenements à double, editer l'événement le jour même pour le faire remonter, changer l'heure, créer l'événement le jour même, etc...)

**Comment by agilare** [comment]
Oui, à voir pour la position des "déjà passés", ça dépend aussi de l'ordre des évnements. Des tests pourraient clarifier.
Pour l'ordre, trier par heure de début permettrait déjà de "nettoyer" ces pratiques (remarque: actuellement éditer un événement ne modifie pas son classement)

Les événements sans heure de début et/ou de fin seraient tous placés en fin de liste, ce qui parait logique et ça inciterait les organisateurs à saisir ces données.

Mais ça "bouleverserait" un peu l'usage du site, après 16 ans d'habitudes. À tester donc. 
Je song aussi à mettre "Derniers événements ajoutés"  dans un onglet en homepage afin de voir ce qu'il y a de neuf plus facilement sur affichage mobile, et afficher davantage que les 6 derniers éven.

**Comment by agilare** [comment]
A simpler idea, without changing order of events : #51

**Comment by agilare** [comment]
A first step has been done in 2025 with the new small menu allowing to select the order of the events : latest (default) or by start time.
The following must be specified, considering also related changes : #105 #51
