### ISSUE TITLE
Event add/edit form : facilitate the selection of the event venue

### ISSUE THREAD

**Issue by agilare** [agilare/ladecadanse#25]
Feature simplifying the entering of the place when adding/editing an event. Currently, on this form a user has to choose between the selection of a place registered on La décadanse (a `<select>` with [Select2](https://select2.org/)) or entering manually place informations : name, address... 

<img width="736" height="297" alt="Image" src="https://github.com/user-attachments/assets/37294267-c56c-4627-87e7-dc4ad310bcbc" />

Often users wrongly choose to enter manually informations despite the place is after all already registered on La décadanse

# Spécifications

## Champs du fieldset "Lieu"

- **Nom du lieu*** (Select2 des lieux enregistrés sur le site et configuration [Dynamic option creation](https://select2.org/tagging); le 2e champ "Nom du lieu" actuel est donc supprimé)
- **Adresse***
- **Localité/quartier***
- **URL**

<img width="743" height="209" alt="Image" src="https://github.com/user-attachments/assets/32f8d411-b449-4af3-9138-8f77a7d4efd1" />

## Cas

L'utilisateur tape le nom dans le champ `<select>`, 2 possibilités : 

1. il **le trouve** parmi ceux enregistrés et le sélectionne (event)
2. les 3 champs suivants sont remplis par les infos du lieu enregistré sélectionné et deviennent `readonly`. Les éventuelles données déjà saisies dans ces trois champs sont remplacées, après confirmation de l'utilisateur 
3. si l'utilisateur désélectionne le lieu (icône ❌)  : reset, les 3 champs suivants sont vidés et leur `readonly` est ôté

OU

1. il ne **le trouve pas** et finit de taper le nom, les 3 champs suivants restent vides
2. il remplit normalement les champs suivants (au moins **Adresse** et **Localité**) 

## Pistes pour alimenter les champs "Adresse", "Localité/quartier", etc. des lieux sélectionnés dans "Nom du lieu" :
- JSON
- `data-` attributes :  ```<option value="123" data-adresse="Sentier des Saules 27" data-localite="Genève" data-url="http://www.arve-ge.ch/a-la-pointe/">Cinéma CDD</option>```

# Tasks
- [ ] pour cette utilisation, explorer les possibilités de Select2
- [ ] gérer rétablissement données saisies au réaffichage du form (s'il a été soumis avec une erreur)
- [ ] event edit avec un lieu enregistré sur le site : préremplir les 3-4 champs suivants
- [ ] ...

## Optionnel
- [ ] dans la liste déroulante "Nom du lieu", en plus du Nom, afficher éventuellement la localité du lieu gris et plus petit, comme déjà fait avec l'URL de l'organisateur dans le champ "Organisateur(s) de l’événement"
